[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"
bson = "2.0"
diesel = { version = "2.1.0", features = ["mysql", "r2d2"] }
r2d2 = "0.8"
actix-cors = "0.7"